# Generated by Django 4.0.3 on 2022-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stack', models.TextField()),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('github', models.URLField(default='https://github.com/maesterzak')),
            ],
        ),
    ]
