# Generated by Django 4.0.3 on 2022-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfolio_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
