# Generated by Django 4.0.3 on 2022-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comments_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
