# Generated by Django 4.0.3 on 2022-03-13 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('55b68ed3-d9bf-4157-986a-e65f55619e2e')),
        ),
    ]
