# Generated by Django 4.0.3 on 2022-03-13 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_author_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('82e67c01-de18-4812-8e05-c2cac6a3045d')),
        ),
        migrations.AddField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('eb54dc77-ff45-4b72-b7f1-42f6d4932353')),
        ),
        migrations.AddField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9c58e771-3c2f-4341-99ce-5e23450b13ec')),
        ),
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('dd381f8a-7ad8-4b28-a537-75a2d34b3398')),
        ),
    ]
