# Generated by Django 4.0.3 on 2022-03-13 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_unique_id_posts_unique_id_threads_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('dc2ced0a-dfb3-464d-86b4-10edf8330f95')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8119578f-6281-42ca-b87d-918fc5929f6c')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d142a8a2-e50c-471a-85bd-ea326e6d5bf1')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a20d5818-4206-4e4b-bfd7-da0f2916d463')),
        ),
    ]
