# Generated by Django 4.0.3 on 2022-03-15 20:06

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c23b8378-7db0-4f85-b361-80da3d18ca62')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('08d957ba-3719-430b-b931-48a4d7ff0d8a')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Empty Content'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ad82fbfe-581a-40a1-9881-b333490fccd5')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a538069a-9cc1-43ba-a22e-5d47c77ccaa6')),
        ),
    ]
