# Generated by Django 4.0.3 on 2022-03-18 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_author_facebook_author_instagram_author_linkdn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('070d075c-fd80-455d-b04a-6ccb8508b565')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('38442c16-90de-46cf-ad52-86f99d0510b1')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('93abaa67-966a-4cf1-a30e-c6464ee818b4')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2a950545-0013-4b44-b2f4-08f4980a35d4')),
        ),
    ]
