# Generated by Django 4.0.3 on 2022-03-18 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b6a7bd00-2f54-4875-a643-6ced1188e0c8')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('4049296f-f92a-4fff-9685-2de976f7b7f4')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('96ce2301-8a92-47c3-ab55-a5b642578c08')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('438f77cc-6f0d-4bb8-9c2a-188d655481cb')),
        ),
    ]
