# Generated by Django 4.0.3 on 2022-03-18 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b62741ef-da6b-4479-97fc-7975446df7ad')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('51faab0a-7979-4e86-9350-86b58bdd5f0e')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('43e56f67-4cd7-44c8-95d1-c4e9fe030c1c')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('695e7cad-b9e6-4ef0-939a-c9a73f7ed590')),
        ),
    ]
