# Generated by Django 4.0.3 on 2022-03-18 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.URLField(default='undefined'),
        ),
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('73c1769c-8b6f-4224-81a4-8cac8d48c1a0')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b5eacef3-8b4f-4738-a2fb-955b2e141e69')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('7a6681b8-f7f8-45b7-a170-1410ee9bf578')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('35ed69b6-1e14-4fe0-ae20-ece664b1eecb')),
        ),
    ]
