# Generated by Django 4.0.3 on 2022-03-18 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_author_facebook_alter_author_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('33ce637f-7666-4527-89a3-b4564aadba53')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('3cb63a0b-e755-4999-b9a9-ffeccc13ac6f')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5fb8c063-afc6-4735-ac0a-759624046405')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('3414a9b1-d68f-479b-8960-8802caa01b49')),
        ),
    ]
