# Generated by Django 4.0.3 on 2022-03-18 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_author_facebook_alter_author_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ef8d7246-6730-41bf-88f8-0d7994342221')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('4e38f777-6ea9-4b3c-8efc-4400fe9f5682')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97fbcdba-bf81-4340-9c8b-f3559624e315')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('27281d5c-8dbf-4d98-b2ab-6b115acf31b1')),
        ),
    ]
