# Generated by Django 4.0.3 on 2022-03-18 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('0480c58d-8edf-4bcc-aba4-5f29f6bfbc19')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('826e3f27-a77a-42ee-addf-9751b0ad4d6e')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b1567026-cbc3-4caf-9dab-923bb740bc1a')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9f9cc7f1-f2b3-4242-b662-7ebe1bb2af83')),
        ),
    ]
