# Generated by Django 4.0.3 on 2022-03-18 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('0f1b9dbc-513a-4793-9810-caa72c2f0bf0')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('f47338e8-9de0-4d87-9eb5-11a59da72968')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('733661ff-3b02-49de-9dda-5df5c5e95abd')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('4053e422-1dac-4743-8c00-6d6640bd7882')),
        ),
    ]
