# Generated by Django 4.0.3 on 2022-03-18 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('083fc489-d2af-456c-b8fc-8624584e8cf5')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('633c3b25-1810-49fb-952f-57be68e4ce38')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('26be6460-a569-4704-814b-4e7e7110edc7')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a42167c0-1e0d-4599-9943-5432a22319cd')),
        ),
    ]
