# Generated by Django 4.0.3 on 2022-03-19 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5e5460e0-f140-4a28-8fc1-f0ed9c322f22')),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('020260a5-1cda-48db-98d2-f06bcdde26fa')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('3109a7e0-c35c-46d8-9229-b1090749f5a8')),
        ),
        migrations.AlterField(
            model_name='threads',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('16531c6b-51b9-4a2a-8d0b-130115585939')),
        ),
    ]
