# Generated by Django 4.0.3 on 2022-03-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_author_unique_id_alter_category_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='threads',
            name='unique_id',
        ),
    ]
