# Generated by Django 4.0.3 on 2022-03-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_author_whatsapp_alter_comments_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
