# Generated by Django 4.0.3 on 2022-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_portfolio_projects_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_projects',
            name='videoSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
