# Generated by Django 4.0.3 on 2022-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_portfolio_projects_videosize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_projects',
            name='videoSize',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
