# Generated by Django 4.0.3 on 2022-03-29 23:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_portfolio_projects_videosize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_projects',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
