# Generated by Django 4.0.3 on 2022-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_projects',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
