# Generated by Django 4.0.3 on 2022-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_portfolio_projects_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='threads',
            name='started',
            field=models.DateField(),
        ),
    ]
