# Generated by Django 4.0.3 on 2022-05-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_posts_published_date_alter_threads_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
